# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopedGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 11, 23, 0, 10, 5, 766824))),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 11, 23, 0, 10, 5, 766824))),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('suported_languages', models.TextField()),
                ('genre', models.TextField()),
                ('full_audio', models.BooleanField(default=False)),
                ('subtitle', models.BooleanField(default=False)),
                ('launched', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 11, 23, 0, 10, 5, 767325))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('birth_day', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2017, 11, 23, 0, 10, 5, 766296))),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='developedgames',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Developer'),
        ),
        migrations.AddField(
            model_name='developedgames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Game'),
        ),
    ]
