# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('genre', models.CharField(max_length=30, verbose_name='Gênero')),
                ('photo', models.ImageField(default='pics/jogos.jpg', upload_to='pics/')),
            ],
        ),
    ]
