# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamCrawler', '0002_remove_games_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='photo',
            field=models.ImageField(default='pics/jogos.jpg', upload_to='pics/'),
        ),
    ]
