# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 18, 12, 33, 673863)),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 18, 12, 33, 674503)),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 18, 12, 33, 675084)),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 18, 12, 33, 673350)),
        ),
    ]
